### PR TITLE
Install docs

### PR DESCRIPTION
**Pull request by tiagojsag**
As part of https://github.com/sonata-project/SonataAdminBundle/issues/1520, this bundle should provide easy install instruction.

### CODE REVIEW

**Comment by rande** [comment]
It will be better to move this into a dedicated docs folder (rst format)

**Comment by tiagojsag** [comment]
I was thinking the same, but thing is, there isn't much to document here, so is it really worth it to create a sub-sub-sub folder to hold 20 lines of docs?

**Comment by rande** [comment]
You are right but it is just a matter of normalisation with all others
bundles.

**Comment by tiagojsag** [comment]
https://github.com/sonata-project/SonatajQueryBundle/pull/11

**Pull request closed without merging**
