### PR TITLE
Update jquery-1.8.3.js

### PR DESCRIPTION
**Pull request by butt**
The same PR https://github.com/sonata-project/SonatajQueryBundle/pull/6

### CODE REVIEW

**Comment by zhil** [comment]
@rande , any chances to merge this PR?

**Comment by rande** [comment]
The 1.8 branch already use jquery 1.8.3

**Comment by zhil** [comment]
@rande thats patch for the JQuery 1.8.3
without it JQuery 1.8.3 doesnt work correctly with uploadify in IE 9

**Comment by zhil** [comment]
@rande can you please check this PR?

**Pull request closed without merging**
